# fly.toml app configuration file generated for mith-strapi on 2024-02-13T11:54:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mith-strapi'
primary_region = 'iad'

[build]

[env]
  DATABASE_CLIENT = 'sqlite'
  DATABASE_FILENAME = '/data/data.db'
  NODE_ENV = 'production'

[[mounts]]
  source = 'database'
  destination = '/data'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
